INSERT INTO media_files (
  id, name, url, public_id, type, mime_type,
  size, folder, alt, caption, created_at, updated_at
) VALUES
  (
    uuid_generate_v4(),
    'Blog Post 1 - Oral Health Tips',
    '/images/blog-1.jpg',
    'blog-1.jpg',
    'image',
    'image/jpeg',
    115503,
    'blog',
    'Dental hygiene and oral health care tips',
    '10 Essential Tips for Maintaining Oral Health',
    NOW(),
    NOW()
  ),
  (
    uuid_generate_v4(),
    'Blog Post 2 - BDS Program',
    '/images/blog-2.jpg',
    'blog-2.jpg',
    'image',
    'image/jpeg',
    110329,
    'blog',
    'Dental education and BDS program guide',
    'Understanding the BDS Program: A Complete Guide',
    NOW(),
    NOW()
  ),
  (
    uuid_generate_v4(),
    'Blog Post 3 - Modern Orthodontics',
    '/images/blog-3.jpg',
    'blog-3.jpg',
    'image',
    'image/jpeg',
    124404,
    'blog',
    'Modern orthodontic treatment options and braces',
    'Modern Orthodontics: Beyond Traditional Braces',
    NOW(),
    NOW()
  ),
  (
    uuid_generate_v4(),
    'Clinic Photo 1',
    '/images/clinic-1.jpg',
    'clinic-1.jpg',
    'image',
    'image/jpeg',
    116898,
    'clinic',
    'Modern dental clinic treatment room',
    'State-of-the-art dental treatment facility',
    NOW(),
    NOW()
  ),
  (
    uuid_generate_v4(),
    'Clinic Photo 2',
    '/images/clinic-2.jpg',
    'clinic-2.jpg',
    'image',
    'image/jpeg',
    168446,
    'clinic',
    'Dental clinic reception and waiting area',
    'Welcoming reception area',
    NOW(),
    NOW()
  ),
  (
    uuid_generate_v4(),
    'Clinic Photo 3',
    '/images/clinic-3.jpg',
    'clinic-3.jpg',
    'image',
    'image/jpeg',
    114592,
    'clinic',
    'Advanced dental equipment and technology',
    'Modern dental equipment',
    NOW(),
    NOW()
  ),
  (
    uuid_generate_v4(),
    'Clinic Photo 4',
    '/images/clinic-4.jpg',
    'clinic-4.jpg',
    'image',
    'image/jpeg',
    55534,
    'clinic',
    'Dental treatment procedure in progress',
    'Professional dental care',
    NOW(),
    NOW()
  ),
  (
    uuid_generate_v4(),
    'Clinic Photo 5',
    '/images/clinic-5.jpg',
    'clinic-5.jpg',
    'image',
    'image/jpeg',
    102899,
    'clinic',
    'Clean and modern clinic interior',
    'Modern clinic environment',
    NOW(),
    NOW()
  ),
  (
    uuid_generate_v4(),
    'Dental Team Photo',
    '/images/team.jpg',
    'team.jpg',
    'image',
    'image/jpeg',
    214109,
    'general',
    'Om Chabahil Dental Hospital team',
    'Our dedicated dental team',
    NOW(),
    NOW()
  ),
  (
    uuid_generate_v4(),
    'Hospital Logo',
    '/images/logo.jpg',
    'logo.jpg',
    'image',
    'image/jpeg',
    55686,
    'general',
    'Om Chabahil Dental Hospital logo',
    'Hospital logo',
    NOW(),
    NOW()
  )
ON CONFLICT (public_id) DO UPDATE SET
  name = EXCLUDED.name,
  url = EXCLUDED.url,
  size = EXCLUDED.size,
  folder = EXCLUDED.folder,
  alt = EXCLUDED.alt,
  caption = EXCLUDED.caption,
  updated_at = NOW();
